config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from system.views import home

urlpatterns = [
    path("", home, name="home"),
    path("cadastros/", include("cadastros.urls")),

    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ppd.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ppd/cadastros/urls.py
from django.urls import path
from .views import (
    lista_cadastro,
    detalhe_cadastro,
    criar_cadastro,
    editar_cadastro,
    deletar_cadastro
)


urlpatterns = [
    path("", lista_cadastro, name="lista_cadastro"),
    path("<int:pk>", detalhe_cadastro, name="detalhe_cadastro"),
    path("novo/", criar_cadastro, name="criar_cadastro"),
    path("<int:pk>/editar", editar_cadastro, name="editar_cadastro"),
    path("<int:pk>/deletar", deletar_cadastro, name="deletar_cadastro"),
]

ppd/users/urls.py
from django.urls import path

from ppd.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ppd/cadastros/models.py
from django.db import models
from system.models import BaseModel
from multiselectfield import MultiSelectField


class Cadastro(BaseModel):
    nome = models.CharField(
        max_length=80,
        blank=False,
        null=False,
        verbose_name='Nome',
    )
    rh = models.CharField(
        max_length=80,
        blank=False,
        null=False,
        verbose_name='RH',
    )
    data_nascimento = models.DateField(
        auto_now=False,
        auto_now_add=False,
        null=False,
        blank=False,
        verbose_name='Data de Nascimento',
    )
    data_diagnostico = models.DateField(
        auto_now=False,
        auto_now_add=False,
        null=False,
        blank=False,
        verbose_name='Data do Diagnóstico',
    )
    telefone = models.CharField(
        max_length=15,
        null=False,
        blank=False,
        verbose_name='Telefone'
    )

    DM1 = 'DM1'
    DM2 = 'DM2'
    MONOGENICO = 'Monogênico'
    POS = 'Pós-transplante'
    GESTACIONAL = 'Gestacional'
    OUTROS = 'Outros'

    DIABETES_TYPE_CHOICES = (
        (DM1, 'DM1'),
        (DM2, 'DM2'),
        (MONOGENICO, 'Monogênico'),
        (POS, 'Pós-transplante'),
        (GESTACIONAL, 'Gestacional'),
        (OUTROS, 'Outros'),
    )
    diabetes = models.CharField(
        max_length=80,
        blank=False,
        null=False,
        choices=DIABETES_TYPE_CHOICES,
        default=DM1,
        verbose_name='Tipo de Diabetes',
    )

    CAD = 'CAD'
    EHH = 'EHH'
    ROTINA = 'Rotina'

    DIAGNOSTICO_TYPE_CHOICES = (
        (CAD, 'CAD'),
        (EHH, 'EHH'),
        (ROTINA, 'Rotina'),
    )
    diagnostico = models.CharField(
        max_length=80,
        blank=False,
        null=False,
        choices=DIAGNOSTICO_TYPE_CHOICES,
        default=CAD,
        verbose_name='Sistomas no Diagnóstico',
    )

    AVE = 'AVE'
    IAM = 'IAM'
    DAC = 'DAC'
    DAP = 'DAP'
    ICC = 'ICC'

    MACROANGIOPATIA_TYPE_CHOICES = (
        (AVE, 'AVE'),
        (IAM, 'IAM'),
        (DAC, 'DAC'),
        (DAP, 'DAP'),
        (ICC, 'ICC'),
    )
    macroangiopatia = MultiSelectField(
        max_length=80,
        blank=True,
        null=True,
        choices=MACROANGIOPATIA_TYPE_CHOICES,
        verbose_name='Macroangiopatia',
    )

    NENHUM = 'Nenhum'
    RETINOPATIA = 'Retinopatia'
    NAO_PROLIFERATIVA = 'Não proliferativa'
    PROLIFERATIVA = 'Proliferativa'

    MICROANGIOPATIA_TYPE_CHOICES = (
        (NENHUM, 'Nenhum'),
        (RETINOPATIA, 'Retinopatia'),
        (NAO_PROLIFERATIVA, 'Não proliferativa'),
        (PROLIFERATIVA, 'Proliferativa'),
    )
    microangiopatia = MultiSelectField(
        max_length=80,
        blank=True,
        null=True,
        choices=MICROANGIOPATIA_TYPE_CHOICES,
        verbose_name='Microangiopatia',
    )

    NENHUM = 'Nenhum'
    NEFROPATIA = 'Nefropatia'
    DIALITICA = 'Dialítica'
    NAO_DIALITICA = 'Não dialítica'
    ALBUMINURIA = 'Albuminúria'

    NEFROPATIA_TYPE_CHOICES = (
        (NENHUM, 'Nenhum'),
        (NEFROPATIA, 'Nefropatia'),
        (DIALITICA, 'Dialítica'),
        (NAO_DIALITICA, 'Não dialítica'),
        (ALBUMINURIA, 'Albuminúria'),
    )
    nefropatia = models.CharField(
        max_length=80,
        blank=True,
        null=True,
        choices=NEFROPATIA_TYPE_CHOICES,
        verbose_name='Nefropatia',
    )

    NENHUM = 'Nenhum'
    NEUROPATIA = 'Neuropatia autonômica'
    HIPOTENSAO = 'Hipotensão postural'
    GASTROPARESIA = 'Gastroparesia'
    DISFUNCAO = 'Disfunção erétil'
    HIPOGLICEMIA = 'Hipoglicemia oligo/assintomática'
    PERIFERICA = 'Neuropatia Periférica'

    NEUROPATIA_TYPE_CHOICES = (
        (NENHUM, 'Nenhum'),
        (NEUROPATIA, 'Neuropatia autonômica'),
        (HIPOTENSAO, 'Hipotensão postural'),
        (GASTROPARESIA, 'Gastroparesia'),
        (DISFUNCAO, 'Disfunção erétil'),
        (HIPOGLICEMIA, 'Hipoglicemia oligo/assintomática'),
        (PERIFERICA, 'Neuropatia Periférica'),
    )
    neuropatia = models.CharField(
        max_length=80,
        blank=True,
        null=True,
        choices=NEUROPATIA_TYPE_CHOICES,
        verbose_name='Neuropatia automômica',
    )

    INSULINA = 'Insulina'
    NPH = 'NPH'
    REGULAR = 'Regular'
    LENTA = 'Análoga lenta'
    RAPIDA = 'Anãloga ultra-rápida'
    BCI = 'BCI'
    DROGAS = 'Drogas orais'
    GLP = 'Agonista de GLP-1'
    DPP = 'Inibidor de DPP-4'
    SGLT = 'Inibidor de SGLT2'
    PIOGLITAZONA = 'Pioglitazona'
    SULFONILUREIAS = 'Sulfoniluréias'
    METFORMINA = 'Metformina'

    MEDICACAO_TYPE_CHOICES = (
        (INSULINA, 'Insulina'),
        (NPH, 'NPH'),
        (REGULAR, 'Regular'),
        (LENTA, 'Análoga lenta'),
        (RAPIDA, 'Análoga ultra-rápida'),
        (BCI, 'BCI'),
        (DROGAS, 'Drogas orais'),
        (GLP, 'Agonista de GLP-1'),
        (DPP, 'Inibidor de DPP-4'),
        (SGLT, 'Inibidor de SGLT2'),
        (PIOGLITAZONA, 'Pioglitazona'),
        (SULFONILUREIAS, 'Sulfoniluréias'),
        (METFORMINA, 'Metformina'),
    )
    medicacao = MultiSelectField(
        max_length=80,
        blank=True,
        null=True,
        choices=MEDICACAO_TYPE_CHOICES,
        verbose_name='Medicação atual',
    )

    HAS = 'HAS'
    DLP = 'DLP'
    NEOPLASIA = 'Neoplasia'

    COMORBIDADES_TYPE_CHOICES = (
        (HAS, 'HAS'),
        (DLP, 'DLP'),
        (NEOPLASIA, 'Neoplasia'),
    )
    comorbidades = MultiSelectField(
        max_length=80,
        blank=True,
        null=True,
        choices=COMORBIDADES_TYPE_CHOICES,
        verbose_name='Comorbidades',
    )

    IAM = 'IAM'
    AVE = 'AVE'
    OUTRAS = 'Outras'

    EVENTOS_TYPE_CHOICES = (
        (IAM, 'IAM'),
        (AVE, 'AVE'),
        (OUTRAS, 'Outras'),
    )
    eventos = models.CharField(
        max_length=80,
        blank=True,
        null=True,
        choices=EVENTOS_TYPE_CHOICES,
        verbose_name='Eventos fatais',
    )

    obs = models.TextField(
        max_length=999,
        blank=True,
        null=True,
        verbose_name='Obs',
    )
    ano = models.DateField(
        auto_now=False,
        auto_now_add=False,
        null=True,
        blank=True,
        verbose_name='Ano',
    )

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Nome'

ppd/system/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ['-created_at']

ppd/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

ppd/cadastros/forms.py
from django import forms
from django.forms import ModelForm
from .models import Cadastro


class CadastroForm(forms.ModelForm):
    class Meta:
        model = Cadastro
        fields = [
                  'telefone', 'nome', 'rh', 'data_nascimento', 'data_diagnostico',
                  'diabetes', 'diagnostico', 'macroangiopatia', 'microangiopatia',
                  'nefropatia', 'neuropatia', 'medicacao',  'comorbidades', 'eventos',
                  'obs', 'telefone', 'ano'
                ]
        widgets = {
            'diabetes': forms.RadioSelect(),
            'diagnostico': forms.RadioSelect(),
            'nefropatia': forms.RadioSelect(),
            'neuropatia': forms.RadioSelect(),
            'eventos': forms.RadioSelect(),
            'obs': forms.Textarea(attrs={'rows': 3, 'cols': 15}),
            }

ppd/system/forms.py
from django import forms
from allauth.account.forms import (
    LoginForm,
)


class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.update({'class': 'form-control', 'type': 'text'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'type': 'text'})

ppd/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

ppd/cadastros/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Cadastro
from .forms import CadastroForm


@login_required
def lista_cadastro(request):
    cadastro = Cadastro.objects.all()
    data = {}
    data['object_list'] = cadastro
    return render(request, 'cadastros/lista_cadastro.html', data)


@login_required
def detalhe_cadastro(request, pk):
    cadastro = get_object_or_404(Cadastro, pk=pk)
    form = CadastroForm(request.POST or None, instance=cadastro)
    return render(request, 'cadastros/detalhe_cadastro.html', {'form': form, 'object': cadastro})


@login_required
def criar_cadastro(request):
    form = CadastroForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('lista_cadastro')
    return render(request, 'cadastros/form_cadastro.html', {'form': form})


@login_required
def editar_cadastro(request, pk):
    cadastro = get_object_or_404(Cadastro, pk=pk)
    form = CadastroForm(request.POST or None, instance=cadastro)
    if form.is_valid():
        form.save()
        return redirect('lista_cadastro')
    return render(request, 'cadastros/form_cadastro.html', {'form': form})


@login_required
def deletar_cadastro(request, pk):
    cadastro = get_object_or_404(Cadastro, pk=pk)
    if request.method == 'POST':
        cadastro.delete()
        return redirect('lista_cadastro')
    return render(request, 'deletar_confirmar.html', {'object': cadastro})

ppd/system/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from cadastros.models import Cadastro


@login_required
def home(request):
    cadastros = Cadastro.objects.all().count()
    return render(request, 'pages/home.html', {
        'cadastros': cadastros,
    })

ppd/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

ppd/templates/cadastros/detalhe_cadastro.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}
{% block breadcrumb %}
<div class="row">
    <div class="col-xl-12">
        <div class="page-title-box">
            <ol class="breadcrumb float-left">
                <li class="breadcrumb-item"><a href="#"> Dashboard </a></li>
                <li class="breadcrumb-item"><a href="{% url 'lista_cadastro' %}"> Cadastros </a></li>
                <li class="breadcrumb-item active"> Detalhe de {{object.nome}} </li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
    <div class="col-xl-12">
        <ul class="nav nav-tabs nav-fill" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active bb0" href="#home" aria-controls="home" role="tab" data-toggle="tab">
                    <em class="fa fa-user"></em> Cadastro do Paciente</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link bb0" href="#profile" aria-controls="profile" role="tab" data-toggle="tab">
                    <em class="fa fa-file"></em> Cadastro do Diagnóstico</a>
            </li>
        </ul>
        <div class="card-box table-responsive">
       <h4 class="m-t-0 header-title"> Cadastro </h4>
            <div class="tab-content p-0 bg-white">
                <div class="tab-pane active" id="home" role="tabpanel">
                    <form class="" method="POST" action="" enctype="multipart/form-data" onsubmit="saveButton.disabled = true; return true;">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-8">
                                {{ form.nome|as_crispy_field }}
                            </div>
                            <div class="col-4">
                                {{ form.rh|as_crispy_field }}
                            </div>
                            <div class="col-4">
                                {{ form.data_nascimento|as_crispy_field }}
                            </div>
                            <div class="col-4">
                                {{ form.data_diagnostico|as_crispy_field }}
                            </div>
                            <div class="col-4">
                                {{ form.telefone|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.diabetes|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.diagnostico|as_crispy_field }}
                            </div>
                        </div>
                </div>
                <div class="tab-pane" id="profile" role="tabpanel">
                        <div class="form-group row">
                            <div class="col-3">
                                {{ form.macroangiopatia|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.microangiopatia|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.medicacao|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.nefropatia|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.neuropatia|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.comorbidades|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.eventos|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.ano|as_crispy_field }}
                            </div>
                            <div class="col-12">
                                {{ form.obs|as_crispy_field }}
                            </div>
                        </div>
                        <a onclick="history.back()" class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span class="btn-label"><i class="fa fa-arrow-left"></i></span>Voltar</button></a>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}

<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function(){
        $("#id_nome").prop("disabled", true);
        $("#id_rh").prop("disabled", true);
        $("#id_data_nascimento").prop("disabled", true);
        $("#id_data_diagnostico").prop("disabled", true);
        $("#id_telefone").prop("disabled", true);
        $("#id_diabetes").prop("disabled", true);
        $("#id_diagnostico").prop("disabled", true);
        $("#id_macroangiopatia").prop("disabled", true);
        $("#id_microangiopatia").prop("disabled", true);
        $("#id_nefropatia").prop("disabled", true);
        $("#id_neuropatia").prop("disabled", true);
        $("#id_medicacao").prop("disabled", true);
        $("#id_comorbidades").prop("disabled", true);
        $("#id_eventos").prop("disabled", true);
        $("#id_ano").prop("disabled", true);
        $("#id_obs").prop("disabled", true);
    });
</script>

{% endblock scripts %}

ppd/templates/cadastros/form_cadastro.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}
{% block breadcrumb %}
<div class="row">
    <div class="col-xl-12">
        <div class="page-title-box">
            <ol class="breadcrumb float-left">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{% url 'lista_cadastro' %}">Cadastros</a></li>
                {% if form.instance.pk %}
                    <li class="breadcrumb-item active">Editar</li>
                {% else %}
                    <li class="breadcrumb-item active">Novo</li>
                {% endif %}
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
    <div class="col-xl-12">
        <ul class="nav nav-tabs nav-fill" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active bb0" href="#home" aria-controls="home" role="tab" data-toggle="tab">
                    <em class="fa fa-user"></em> Cadastro do Paciente</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link bb0" href="#profile" aria-controls="profile" role="tab" data-toggle="tab">
                    <em class="fa fa-file"></em> Cadastro do Diagnóstico</a>
            </li>
        </ul>
        <div class="card-box table-responsive">
       <h4 class="m-t-0 header-title"> Cadastro </h4>
            <div class="tab-content p-0 bg-white">
                <div class="tab-pane active" id="home" role="tabpanel">
                    <form class="" method="POST" action="" enctype="multipart/form-data" onsubmit="saveButton.disabled = true; return true;">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-8">
                                {{ form.nome|as_crispy_field }}
                            </div>
                            <div class="col-4">
                                {{ form.rh|as_crispy_field }}
                            </div>
                            <div class="col-4">
                                {{ form.data_nascimento|as_crispy_field }}
                            </div>
                            <div class="col-4">
                                {{ form.data_diagnostico|as_crispy_field }}
                            </div>
                            <div class="col-4">
                                {{ form.telefone|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.diabetes|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.diagnostico|as_crispy_field }}
                            </div>
                        </div>
                </div>
                <div class="tab-pane" id="profile" role="tabpanel">
                        <div class="form-group row">
                            <div class="col-3">
                                {{ form.macroangiopatia|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.microangiopatia|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.medicacao|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.nefropatia|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.neuropatia|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.comorbidades|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.eventos|as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ form.ano|as_crispy_field }}
                            </div>
                            <div class="col-12">
                                {{ form.obs|as_crispy_field }}
                            </div>
                        </div>
                        <button class="primaryAction btn btn-sm btn-success waves-effect waves-light"><span class="btn-label"><i class="fa fa-check"></i></span>Salvar</button>
                        <a onclick="history.back()" class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span class="btn-label"><i class="fa fa-arrow-left"></i></span>Voltar</button></a>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}

<script>
    $(document).ready(function(){
      var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
      },
      spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
          }
      };

      $('#id_telefone').mask(SPMaskBehavior, spOptions);
    });
</script>

<script>
    $(document).ready(function(){
        $("#id_data_nascimento").mask("99/99/9999");
        $("#id_data_diagnostico").mask("99/99/9999");
        $("#id_ano").mask("99/99/9999");
    });
</script>

{% endblock scripts %}